from v1.views.estabelecimento_views import EstabelecimentoView
from v1.views.comentario_views import ComentarioViewSet
from v1.views.resposta_views import RespostaViewSet
from v1.views.resumo_de_avaliacoes_views import ResumoDeAvaliacoesViewSet
from v1.views.tag_views import TagViewSet
from v1.views.estabelecimento_tag_views import EstabelecimentoTagView